tune-cartpole:
    env: CartPole-v0
    alg: DQN
    max_trials: 20
    resources:
       cpu: 1
    stop:
        episode_reward_mean: 200
        time_total_s: 1
    parameters:
        schedule_max_timesteps: 100000
        lr: .001
        sample_batch_size:
            grid_search: [1, 2, 4]
        exploration_fraction:
            eval: random.choice([.01, .02])
        exploration_final_eps: 0.02
        dueling:
            grid_search: [True, False]
        hiddens: []
        model:
            fcnet_hiddens: [64]
            fcnet_activation: relu
